[window]
opacity = 0.9
padding.x = 10
padding.y = 10

[colors]
primary.background = "#000000"
cursor = { cursor = "#15fe00", text = "#000000" }

[font]
normal.family = "UbuntuMono Nerd Font"
bold.family = "UbuntuMono Nerd Font"
italic.family = "UbuntuMono Nerd Font"
bold_italic.family = "UbuntuMono Nerd Font"
offset.y = 4

size = 18
